---
driver:
  customize:
    memory: 2048

driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: ndenv
    run_list:
      - recipe[container::ndenv]
  - name: phpenv
    run_list:
      - recipe[container::phpenv]
  - name: pyenv
    run_list:
      - recipe[container::pyenv]
  - name: rbenv
    run_list:
      - recipe[container::rbenv]
    excludes:
      - ubuntu-14.04
  - name: builder
    run_list:
      - recipe[container::builder]
    excludes:
      - ubuntu-12.04
