AllCops:
  Include:
    - metadata.rb
    - Rakefile
    - '**/Gemfile'
    - attributes/**/*
    - definitions/**/*
    - libraries/**/*
    - providers/**/*
    - recipes/**/*
    - resources/**/*
    - spec/**/*
    - test/**/*
  Exclude:
    - cookbooks/**/*
    - dockerfiles/**/*
    - vendor/**/*
